[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/pallet-did',
   	'pallets/pallet-schema',
    'pallets/substrate-validator-set',
	'pallets/substrate-rbac',
	'pallets/registrar',
    'runtime'
]
