[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/pallet-did',
    'pallets/pallet-schema',
    'pallets/pallet-credential',
    'pallets/registrar',
    'runtime'
]
